In [ ]:
import numpy as np

In [ ]:
x = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])

x.shape

(2, 6)

In [ ]:
y = x.reshape(4, 3)

y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
import random as rnd

%timeit py_list = [rnd.randint(1, 10) for i in range(0, 6000000)]

5.53 s ± 451 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit np_array = np.random.randint(1, 10, 6000000)

135 ms ± 12.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
l1 = [2, 4, 6, 8, 10]

l2 = l1 + [100, 200]

l2

[2, 4, 6, 8, 10, 100, 200]

In [ ]:
nd1 = np.array([2, 4, 6, 8, 10])
#tens = np.full(5, 10)

nd2 = nd1 * 10

#[10, 10, 10, 10, 10]

nd2

array([ 20,  40,  60,  80, 100])

In [ ]:
nd3 = nd1 ** 2

nd3

array([  4,  16,  36,  64, 100])

In [ ]:
nd4 = nd1 + 3

nd4

array([ 5,  7,  9, 11, 13])

In [ ]:
type(nd4)

numpy.ndarray

In [ ]:
xyz = nd4.tolist()

type(xyz)

list

In [ ]:
nd5 = np.array([12, 13, 14, 16])

nd5 != nd5

array([False, False, False, False])